//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EccomUpload
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Customer_Reg_Table
    {
        public int Customer_ID { get; set; }
        [DisplayName("First name")]
        public string Customer_First_Name { get; set; }
        [DisplayName("Second name")]
        public string Customer_Second_Name { get; set; }
        [DisplayName("Phone")]
        public string Customer_Phone_Number { get; set; }
        [DisplayName("Nearest Primary School")]
        public string Customer_Nearest_Primary { get; set; }
    }
}
