//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EccomUpload
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Web;

    public partial class product
    {
        public int ID { get; set; }
        [DisplayName("Upload")]
        public string Product_Image { get; set; }
        [DisplayName("Item")]
        public HttpPostedFileBase ImageFile { get; set; }
        [DisplayName("Item name")]
        public string Product_Name { get; set; }
        [DisplayName("Item description")]
        public string Product_Desc { get; set; }
        [DisplayName(" Item Price")]
        public string Product_Price { get; set; }
    }
}
